title: Spellzed
description: Writing about DFIR
baseurl: /spellzedblog
show_downloads: false
excerpt_separator: <!-- excerpt-end -->

remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-toc
  - jekyll-remote-theme

gems:
  - jekyll-toc

toc:
  min_level: 1
  max_level: 6
  no_toc_section_class: no_toc_section
  list_class: toc-list
  sublist_class: toc-sublist